name: igvf_pseudobulking_test
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - anndata
  - bioconda::ucsc-bedgraphtobigwig
  - bioconda::bedtools
  - bioconda::macs3
  - jq
  - pandas
  - numba
  - numpy
  - gzip
  - pandas
  - scanpy
  - pip
  - pip:
    - requests
